site_name: 6ch's Website
site_author: 6ch.
site_url: https://6chHenry.github.io
site_description: 6ch. 的个人网站
repo_url: https://github.com/6chHenry/6chHenry.github.io
repo_name: 6ch.'s Site
copyright: Copyright &copy; 2024 - Present <a href="https://github.com/6chHenry" target="_blank" rel="noopener">6ch.</a>




  
theme:
  name: material
  language: en
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - header.autohide
    # - navigation.instant.progress
    # - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.prune
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: white # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: light mode # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: dark mode
  font:
    text: JetBrains Mono
  favicon: img/avatar1.jpg
  icon:
    logo: material/coffee
    repo: fontawesome/brands/git-alt
    edit: material/pencil

  static_templates:
    - 404.html

plugins:
  - blogging:
      locale: en
      dirs:
        - notes
      show_total: true
      features:
        tags:
          index_page: tags/
          insert: top
  - callouts
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - index.md
        - about/index.md
        - summary/index.md
        - notes/index.md
        - diaries/index.md
  - minify:
      minify_html: true
  - mkdocs-video:
      video_muted: True
      video_controls: True
      mark: "video"
  # - rss:
  #     enabled: !ENV [CI, false]
  #     use_material_social_cards: false
  - search
  - statistics:
      words_per_minute: 200
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - md_in_html
  - nl2br
  - pymdownx.arithmatex: # latex支持
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      auto_title: true # 显示编程语言名称
      linenums: true # 显示行号
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      permalink: true
      toc_depth: 4
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
# - https://busuanzi.icodeq.com/busuanzi.pure.mini.js
# - js/toc.js
extra_css:
  - css/custom.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - css/fold_toc.css
  - css/card.css
  - css/flink.css
  - css/tasklist.css
extra:
  social:
    - icon: /fontawesome/brands/github
      link: https://github.com/6chHenry/
      name: GitHub
    - icon: /fontawesome/brands/qq
      link: /img/qq.png
      name: 加加我的QQ
    - icon: /fontawesome/brands/weixin
      link: /img/wechat.png
      name: 加加我的微信
    # - icon: /fontawesome/brands/zhihu
    #   link: https://www.zhihu.com/people/Kinnariya
      name: Zhihu
    - icon: fontawesome/solid/paper-plane
      link: mailto:2313287840@qq.com
      name: send email to me!
    # - icon: fontawesome/solid/rss
    #   link: /feed_rss_created.xml
    #   name: RSS created
    # - icon: fontawesome/solid/rss
    #   link: /feed_rss_updated.xml
    #   name: RSS updatedfeed_rss_created.xml
nav: 
  - 主页: index.md
  - 笔记:
    - index: notes/index.md
    - EECS 498(Deep Learning for Computer Vision): 
      - 第一节(Linear Classifiers): notes/EECS498/Linear Classifiers.md
      - 第二节(Optimization): notes/EECS498/Optimization.md
      - 第一次作业(pytorch & KNN): notes/EECS498/A1.md
      - 第三节(Neural Network): notes/EECS498/Neural Network.md
      - 第四节(Back Propagation): notes/EECS498/Back Propagation.md
      - 矩阵求导: notes/EECS498/Derivative of Matrix.md
      - 第二次作业(Linear Classifiers): notes/EECS498/A2.md
      - 第二次作业(Two Layer Net): notes/EECS498/2-layer-network.md
    - 概率统计（荣誉）(MATH1207H):
      - 第二次讨论: notes/Probability/讨论2.md
      - 第三次讨论: notes/Probability/讨论3.md
      - 第四次讨论: notes/Probability/讨论4.md
    - 数据结构（荣誉）(CS0501H):
      - 线性表: notes/CS0501H/链表.md
    - 从零构建GPT(Karpathy):
      - Micrograd: notes/GPT/micrograd.md
      - Makemore(First Status): notes/GPT/makemore.md
      - Makemore(MLP): notes/GPT/makemoreMLP.md
      - Makemore(Activation): notes/GPT/makemoreActivation.md
      - Makemore(Become a Backprop Ninja): notes/GPT/makemoreNinja.md
      - Makemore(Convolution Layer): notes/GPT/makemoreComnet.md
      - ShakespeareGPT: notes/GPT/ShakespeareGPT.md
      - Attention is All You Need: notes/GPT/Attention is All You Need.md
      - Dive into GPT: notes/GPT/diveintogpt.md
  - 日记:
    - index: diaries/index.md
    - 2024年:
      - 10月:
        - "18岁生日快乐!": summary/写给18岁的信.md
      - 12月: 
        - "20241226": diaries/2024/20241226.md
        - "20241231": diaries/2024/20241231.md
    - 2025年:
      - 1月: diaries/2025/20250101.md
      - 2月: diaries/2025/20250228.md
      - 3月: 
        - "3.1": diaries/2025/20250301.md
        - "3.2": diaries/2025/20250302.md
        - "3.3": diaries/2025/20250303.md
        - "3.4": diaries/2025/20250304.md
        - "3.5": diaries/2025/20250305.md
        - "3.12": diaries/2025/20250312.md
        - "3.15": diaries/2025/20250315.md
        - "3.16": diaries/2025/20250316.md
        - "3.17": diaries/2025/20250317.md
        - "3.18": diaries/2025/20250318.md
        - "3.21": diaries/2025/20250321.md
        - "3.22": diaries/2025/20250322.md
  - 总结:
    - index: summary/index.md
    - "影评":
      - "3 Idiots": summary/Movies/3 Idiots.md
    - "音乐":
      - "孤儿仔 --Eason Chan": summary/Music/孤儿仔.md
    - "我的高中": summary/高中回忆录.md
    - "大一上":
      - "下半期计划": summary/下半期计划.md
      - "期末复习计划": summary/Review Plan.md
      - "复盘": summary/我的大一上学期.md
    - "大一下":
      - "规划": summary/具体计划.md
    - "睡眠": summary/睡眠的重要性.md
  - 网站:
    - index: websites/index.md
    - LLM: websites/LLM.md
  - 关于我: about/index.md

